### ISSUE TITLE
BOM update, dropped dependencies and "No version provided" warning

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#2982]
Hi,

With the following recipe:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus30.Quarkus3
recipeList:
  - org.openrewrite.maven.ChangePropertyValue:
      key: quarkus.platform.version
      newValue: 3.0.0.Alpha5
  - org.openrewrite.maven.ChangePropertyValue:
      key: quarkus.version
      newValue: 3.0.0.Alpha5
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: org.glassfish
      oldArtifactId: jakarta.el
      newGroupId: org.glassfish.expressly
      newArtifactId: expressly
```

I end up with the following diff:

```diff
diff --git a/pom.xml b/pom.xml
index af5de4f..1d118f7 100644
--- a/pom.xml
+++ b/pom.xml
@@ -16,7 +16,7 @@
         <maven.compiler.release>17</maven.compiler.release>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
-        <quarkus.version>2.16.1.Final</quarkus.version>
+        <quarkus.version>3.0.0.Alpha5</quarkus.version>
         <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
         <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
         <surefire-plugin.version>3.0.0-M9</surefire-plugin.version>
@@ -63,8 +63,8 @@
             <artifactId>quarkus-cache</artifactId>
         </dependency>
         <dependency>
-            <groupId>org.glassfish</groupId>
-            <artifactId>jakarta.el</artifactId>
+            <groupId>org.glassfish.expressly</groupId>
+            <artifactId>expressly</artifactId>
         </dependency>
         <dependency>
             <groupId>com.hrakaroo</groupId>
```

Which is what I would expect.

But if I change the recipe to use `UpgradeDependencyVersion`:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus30.Quarkus3
recipeList:
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: io.quarkus
      artifactId: '*'
      newVersion: 3.x
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: io.quarkus.platform
      artifactId: '*'
      newVersion: 3.x
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: org.glassfish
      oldArtifactId: jakarta.el
      newGroupId: org.glassfish.expressly
      newArtifactId: expressly
```

I end up with the following diff:

```diff
diff --git a/pom.xml b/pom.xml
index af5de4f..85e8183 100644
--- a/pom.xml
+++ b/pom.xml
@@ -16,7 +16,7 @@
         <maven.compiler.release>17</maven.compiler.release>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
-        <quarkus.version>2.16.1.Final</quarkus.version>
+        <quarkus.version>3.0.0.Alpha5</quarkus.version>
         <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
         <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
         <surefire-plugin.version>3.0.0-M9</surefire-plugin.version>
@@ -62,9 +62,9 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-cache</artifactId>
         </dependency>
-        <dependency>
-            <groupId>org.glassfish</groupId>
-            <artifactId>jakarta.el</artifactId>
+        <!--~~(No version provided)~~>--><dependency>
+            <groupId>org.glassfish.expressly</groupId>
+            <artifactId>expressly</artifactId>
         </dependency>
         <dependency>
             <groupId>com.hrakaroo</groupId>
```

As you can see, OpenRewrite can't find the version for the old artifact at some point and adds an error: `<!--~~(No version provided)~~>-->`.

From what I can see, this is me hitting https://github.com/openrewrite/rewrite/issues/2691 but I'm unsure using `retainVersions` is actually viable in my case as I have dozens of artifacts who have disappeared from the radar (we moved from Jakarta EE 9 to Jakarta EE 10 among other things).
I could probably list them all but I'm also pretty sure we will forget to add some at some point.

I wonder if there could be a better way of handling this, as I'm pretty sure it's going to be a common problem?

Is this comment in the pom really necessary?
I mean:
- you can have a warning in the OpenRewrite logs
- if you haven't handled this problem in your recipes, you will end up with a Maven error anyway when trying to build the project

Another option, but I'm not sure it's actually doable: could the comment be added inside the `<dependency>` block and then we could reevaluate it when the dependency is changed (and it would stay around if the dependency has not been adjusted)?

Thanks.

**Comment by knutwannheden** [comment]
I was able to reproduce the issue using a simple example. I will look into it and see what is going on.

**Comment by gsmet** [comment]
@knutwannheden fwiw I think it’s the intended behavior. I’m just wondering if we could make it better.

**Comment by knutwannheden** [comment]
@gsmet This issue has come up before and the Maven plugin is not supposed to write these markers back out after executing the recipes. I have now fixed this in https://github.com/openrewrite/rewrite-maven-plugin/commit/8d3a79908c0cd5597095b1b4aa02907f2a223a8b which will be available in the next release (you can test it with the current 4.43.0-SNAPSHOT release). Please reopen if you still notice any problems.

**Comment by gsmet** [comment]
@knutwannheden I just tested this (sorry for the delay) and I don't think it's fixed.

I still end up with:
```
+        <!--~~(No version provided)~~>--><dependency>
+            <groupId>org.glassfish.expressly</groupId>
+            <artifactId>expressly</artifactId>
```
in my diff.

**Comment by knutwannheden** [comment]
That is odd. I would have expected this to be fixed with version [4.43.0](https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v4.43.0) of the Maven plugin. I will try to verify.

**Comment by gsmet** [comment]
I think this has been fixed now. I haven't encountered it for a while.

I think one of the issue is that we were updating the BOM version property directly instead of updating the BOM itself. And updating a property doesn't update the model (which might cause problems in some cases like this one).
